language: perl
perl:
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
before_install:
  - cpanm -n Devel::Cover::Report::Coveralls
  - cover -delete 
script:
  perl Build.PL && ./Build build && cover -test -report coveralls
